### ISSUE TITLE
Loss of Data when using read_and_upload_file_to_dash function

### ISSUE THREAD

**Issue by eba99** [ComotionLabs/comotion-sdk#56]
**Describe the bug**
I push a field which looks like this, for example: 153.100

This is a string, not a float. The create_gzipped_csv_stream_from_df function interprets this value as a float, and so converts it to a value of 153.1 before sending to Dash.

**Comment by timalive** [comment]
@eba99 is this resolved?  Does it require a further code change?

**Comment by eba99** [comment]
Yes this is resolved.
________________________________
